---
name: cds411-dev
channels:
  - defaults
  - jkglasbrenner
  - conda-forge
dependencies:
  - autopep8=1.4
  - black
  - cython
  - flake8
  - ipywidgets
  - jedi
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - libcurl
  - matplotlib
  - nodejs
  - numpy-base
  - numpy
  - pandas
  - pandoc=2.2.3.2-0
  - pyhamcrest=1.9.0
  - python=3.6.5
  - pytest
  - r-base=3.5.0
  - r-curl
  - rise
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - yapf=0.23.0
  - pip:
    - cite2c
    - ipympl
    - grip
    - importmagic
    - jupyterlab_code_formatter
    - jupyterlab_git
    - jupyterlab_github
    - jupyterlab_templates
    - nbdime
    - pip==18.1
    - plotly
    - pydocstyle
    - rope
    - rpy2
...
