---
name: cds411-dev
channels:
  - defaults
  - jkglasbrenner
  - conda-forge
dependencies:
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - matplotlib
  - numpy-base
  - numpy
  - pandas
  - pyhamcrest=1.9.0
  - python=3.6.5
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - pip:
    - ipympl
    - pip==18.1
    - plotly
...
